// Generated by CoffeeScript 1.9.3

/*
  Defining a class Job, which will create a campaign
  from a single row in the csv
 */

(function() {
  var CronJob, WatchJob, events, moment;

  events = require('events');

  CronJob = require('cron').CronJob;

  moment = require('moment');


  /*
    Conf object: Contains the configuration for the job
    fields:
      type: "daily", "hourly", "once"
      time: if type = "daily" then time of day (timestamp or date object)
            if type = "hourly" then minute
            if type = "once" then date time timestamp
      campaign: name
   */

  WatchJob = function(conf) {
    var job, self, setup, triggerEvent;
    self = this;
    self.conf = conf;
    events.EventEmitter.call(self);
    triggerEvent = {
      campaign: self.conf.campaign
    };
    self.emitEvent = function() {
      return self.emit('TestEvent', triggerEvent);
    };
    setup = (function() {
      switch (self.conf.type) {
        case "hourly":
          return moment(self.conf.time).format('00 mm * * * *');
        case "daily":
          return moment(self.conf.time).format('00 mm */h * * *');
        case "once":
          return new Date(self.conf.time);
      }
    })();
    console.log("setup: " + setup);
    job = new CronJob(setup, function() {
      return self.emitEvent();
    }, function() {
      return console.log("finished");
    }, true);
    return console.log('created WatchJob');
  };

  WatchJob.prototype.__proto__ = events.EventEmitter.prototype;

  module.exports = {
    Job: WatchJob,
    createJob: function(uconf) {
      return new WatchJob(uconf);
    }
  };

}).call(this);
