// Generated by CoffeeScript 1.9.3

/*
  Parse the given csv
 */

(function() {
  var csv, parse;

  csv = require('csv');

  parse = function(downloadStream) {
    return downloadStream.pipe(csv.parse()).pipe(csv.transform(function(record) {
      return record.map(function(value) {
        return value;
      });
    }));
  };

}).call(this);
