// Generated by CoffeeScript 1.9.3
(function() {
  var app, express, port, server;

  express = require('express');

  app = express();

  server = require('http').createServer(app);

  port = 8080;

  server.listen(port, function() {
    return console.log("listening on port " + port);
  });

}).call(this);
