// Generated by CoffeeScript 1.9.3
(function() {
  var conf, moment, myJob, myListener, server, testJob;

  myJob = require('./modules/myJob');

  myListener = require('./modules/myListener');

  moment = require('moment');

  conf = {
    type: 'hourly',
    campaign: 'TCamp',
    time: moment().add(1, 'm').hour(1)
  };

  console.log("current = " + (moment().format('hh:mm a')));

  console.log("time = " + (moment(conf.time).format('hh:mm a')));

  testJob = new myJob.Job(conf);

  testJob.on('TestEvent', myListener);

  server = require('http').createServer();

  server.listen(8080, function() {
    return console.log('listening on port 8080');
  });

}).call(this);
